export const WEATHER_LIST_REQUEST = 'WEATHER_LIST_REQUEST';
export const WEATHER_LIST_SUCCESS = 'WEATHER_LIST_SUCCESS';
export const WEATHER_LIST_FAIL = 'WEATHER_LIST_FAIL';

export const WEATHER_LIST_CEL_REQUEST = 'WEATHER_LIST_CEL_REQUEST';
export const WEATHER_LIST_CEL_SUCCESS = 'WEATHER_LIST_CEL_SUCCESS';
export const WEATHER_LIST_CEL_FAIL = 'WEATHER_LIST_CEL_FAIL';
